name: safe_ping
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  # UI & Icons
  cupertino_icons: ^1.0.8

  # Map & Location
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^13.0.3

  # Networking
  http: ^1.3.0
  image_picker: ^1.1.2
  image: ^4.1.3
  flutter_map_cancellable_tile_provider: ^3.1.0
  geolocator_web: ^4.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
